### ISSUE TITLE
Setting setRender YUCIImageRenderingSuggestedRenderer giving error

### ISSUE THREAD

**Issue by shoaibhassanWhizpool** [YuAo/YUCIImageView#4]
When set renderer using this
 [backgroundImgView setRenderer:YUCIImageRenderingSuggestedRenderer];
Giving error for implicit conversion of non-Objective-C pointer type id <YUCIImageRenderingSuggestedRenderer>

**Comment by YuAo** [comment]
[backgroundImgView setRenderer:YUCIImageRenderingSuggestedRenderer()];

**Comment by shoaibhassanWhizpool** [comment]
Thanks for help,it worked.
